---
version: "3.8"

services:

  caddy:
    image: lucaslorentz/caddy-docker-proxy
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == manager
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    networks:
      - overlaynet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/gluster/appdata/caddy:/data
      - /mnt/gluster/appdata/caddy:/config

  flame:
    image: pawelmalak/flame:multiarch
    deploy:
      replicas: 1
      labels:
        caddy: cafio.co
        caddy.reverse_proxy: "{{upstreams 5005}}"
    networks:
      - overlaynet
    environment:
      TZ: ${TZ}
      PASSWORD: ${PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/gluster/appdata/flame:/app/data

  pihole:
    image: cbcrowe/pihole-unbound:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        flame.type: app
        flame.name: PiHole
        flame.icon: pi-hole
        flame.url: http://swarm.lan:8080/admin/
        flame.visibility: hidden
    ports:
      - target: 80
        published: 8080
        mode: ingress
      - target: 53
        published: 53
        protocol: udp
        mode: ingress
      - target: 53
        published: 53
        protocol: tcp
        mode: ingress
    networks:
      - overlaynet
    environment:
      TZ: ${TZ}
      DHCP_ACTIVE: "false"
      PIHOLE_DOMAIN: lan
      PIHOLE_DNS_: 127.0.0.1#5335
      WEBPASSWORD: ${PASSWORD}
      WEBTHEME: default-dark
      DNSSEC: "true"
      DNSMASQ_LISTENING: local
      REV_SERVER: "true"
      REV_SERVER_DOMAIN: "lan"
      REV_SERVER_TARGET: "192.168.45.1"
      REV_SERVER_CIDR: "192.168.45.0/24"
    volumes:
      - /mnt/gluster/appdata/pihole:/etc/pihole:rw
      - /mnt/gluster/appdata/pihole/unbound:/etc/dnsmasq.d:rw

networks:
  overlaynet:
    driver: overlay
    name: overlaynet