---
version: "3.8"

services:

  pairdrop:
    image: linuxserver/pairdrop:latest
    deploy:
      replicas: 1
      labels:
        caddy: drop.cafio.co
        caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - overlaynet
    environment:
      TZ: ${TZ}
    tmpfs:
      - /config
    labels:
      - flame.type=app
      - flame.name=Pairdrop
      - flame.icon=share-variant
      - flame.url=https://drop.${DOMAIN}/

  nextcloud:
    image: nextcloud:latest
    deploy:
      replicas: 1
      labels:
        caddy: cloud.cafio.co
        caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - overlaynet
    environment:
      TZ: ${TZ}
      NEXTCLOUD_ADMIN_USER: casey
      NEXTCLOUD_ADMIN_PASSWORD: ${PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.${DOMAIN}
      SQLITE_DATABASE: nextcloud
    volumes:
      - ${APPDATA_MNT}/nextcloud:/var/www/html
    labels:
      - flame.type=app
      - flame.name=Cloud
      - flame.icon=cloud
      - flame.url=https://cloud.${DOMAIN}/

  microbin:
    image: danielszabo99/microbin:latest
    deploy:
      replicas: 1
      labels:
        caddy: bin.cafio.co
        caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - overlaynet
    environment:
      TZ: ${TZ}
      MICROBIN_ADMIN_USERNAME: admin
      MICROBIN_ADMIN_PASSWORD: ${PASSWORD}
      MICROBIN_EDITABLE: 'true'
      MICROBIN_HIGHLIGHTSYNTAX: 'true'
      MICROBIN_BIND: '0.0.0.0'
      MICROBIN_PRIVATE: 'true'
      MICROBIN_PUBLIC_PATH: https://bin.${DOMAIN}/
      MICROBIN_SHOW_READ_STATS: 'true'
      MICROBIN_TITLE: cafio
      MICROBIN_ENABLE_BURN_AFTER: 'true'
      MICROBIN_WIDE: 'true'
      MICROBIN_QR: 'true'
      MICROBIN_EXTERNAL_PASTA: 'true'
      MICROBIN_ENABLE_READONLY: 'true'
      MICROBIN_ENCRYPTION_CLIENT_SIDE: 'true'
      MICROBIN_ENCRYPTION_SERVER_SIDE: 'true'
      MICROBIN_DISABLE_TELEMETRY: 'true'
    tmpfs:
      - /app/microbin_data
    labels:
      - flame.type=app
      - flame.name=Microbin
      - flame.icon=delete-variant
      - flame.url=https://bin.${DOMAIN}/
  
  code:
    image: linuxserver/vscodium:latest
    deploy:
      replicas: 1
      labels:
        caddy: code.cafio.co
        caddy.reverse_proxy: "{{upstreams 3000}}"
        caddy.basicauth:
        caddy.basicauth.swarm: $2a$12$8V1u/O/1LuzQDcV56hxX0ekowne/RKeBi6jlT1vLNo0DkdQbFrnKm
    networks:
      - overlaynet
    environment:
      TZ: ${TZ}
    volumes:
      - ${APPDATA_MNT}/vscode:/config
    labels:
      - flame.type=app
      - flame.name=VSCode
      - flame.icon=microsoft-visual-studio
      - flame.url=https://code.${DOMAIN}/

  vaultwarden:
    image: vaultwarden/server:latest
    deploy:
      replicas: 1
      labels:
        caddy: vault.cafio.co
        caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - overlaynet
    environment:
      TZ: ${TZ}
      DOMAIN: https://vault.${DOMAIN}/
      SENDS_ALLOWED: 'true'
      EMERGENCY_ACCESS_ALLOWED: 'true'
      ADMIN_TOKEN: ''
      WEB_VAULT_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'false'
      SIGNUPS_VERIFY: 'false'
      SIGNUPS_DOMAINS_WHITELIST: ${DOMAIN}
      YUBICO_CLIENT_ID: '92307'
      YUBICO_SECRET_KEY: 72o9iOvaz1yUO+6MomnE7EkPNgw=
    volumes:
      - ${APPDATA_MNT}/vaultwarden:/data
    labels:
      - flame.type=app
      - flame.name=Vaultwarden
      - flame.icon=lock
      - flame.url=https://vault.${DOMAIN}/

  gitea:
    image: gitea/gitea:latest
    deploy:
      replicas: 1
      labels:
        caddy: git.cafio.co
        caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - overlaynet
    environment:
      TZ: ${TZ}
      PROTOCOL: https
      DOMAIN: git.${DOMAIN}
      HTTP_PORT: '3000'
      APP_NAME: Gitea
      SHOW_USER_EMAIL: 'false'
      REVERSE_PROXY_TRUSTED_PROXIES: 127.0.0.0/8,::1/128, 192.168.45.0/24, ${DOMAIN}
      EMAIL_DOMAIN_ALLOWLIST: ${DOMAIN}
    volumes:
      - ${APPDATA_MNT}/gitea/config:/data/gitea
      - ${APPDATA_MNT}/gitea/data:/var/lib/gitea
    labels:
      - flame.type=app
      - flame.name=Gitea
      - flame.icon=git
      - flame.url=https://git.${DOMAIN}/

networks:
  overlaynet:
    external: true