---
version: "3.8"

services:

  pairdrop:
    image: linuxserver/pairdrop:latest
    deploy:
      replicas: 1
    networks:
      - overlaynet
    environment:
      - TZ
    tmpfs:
      - /config
    labels:
      - flame.type=app
      - flame.name=Pairdrop
      - flame.icon=share-variant
      - flame.url=https://drop.${DOMAIN}/

  nextcloud:
    image: nextcloud:latest
    deploy:
      replicas: 1
    networks:
      - overlaynet
    environment:
      - TZ
      - NEXTCLOUD_TRUSTED_DOMAINS
      - NEXTCLOUD_TRUSTED_DOMAIN
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - SQLITE_DATABASE
      - OBJECTSTORE_S3_HOST
      - OBJECTSTORE_S3_BUCKET
      - OBJECTSTORE_S3_KEY
      - OBJECTSTORE_S3_SECRET
      - OBJECTSTORE_S3_PORT
      - OBJECTSTORE_S3_SSL
      - OBJECTSTORE_S3_USEPATH_STYLE
      - OBJECTSTORE_S3_AUTOCREATE
    volumes:
      - ${APPDATA_MNT}/nextcloud:/var/www/html
    labels:
      - flame.type=app
      - flame.name=Cloud
      - flame.icon=cloud
      - flame.url=https://cloud.${DOMAIN}/

  onlyoffice:
    image: onlyoffice/documentserver:latest
    deploy:
      replicas: 1
    networks:
      - overlaynet
    environment:
      - TZ
    tmpfs:
      - /var/log/onlyoffice

  microbin:
    image: danielszabo99/microbin:latest
    networks:
      - overlaynet
    environment:
      - TZ
      - MICROBIN_ADMIN_USERNAME
      - MICROBIN_ADMIN_PASSWORD
      - MICROBIN_EDITABLE
      - MICROBIN_HIGHLIGHTSYNTAX
      - MICROBIN_PORT
      - MICROBIN_BIND
      - MICROBIN_PRIVATE
      - MICROBIN_PUBLIC_PATH
      - MICROBIN_SHOW_READ_STATS
      - MICROBIN_TITLE
      - MICROBIN_ENABLE_BURN_AFTER
      - MICROBIN_WIDE
      - MICROBIN_QR
      - MICROBIN_EXTERNAL_PASTA
      - MICROBIN_ENABLE_READONLY
      - MICROBIN_ENCRYPTION_CLIENT_SIDE
      - MICROBIN_ENCRYPTION_SERVER_SIDE
      - MICROBIN_DISABLE_TELEMETRY
    tmpfs:
      - /app/microbin_data
    labels:
      - flame.type=app
      - flame.name=Microbin
      - flame.icon=delete-variant
      - flame.url=https://bin.${DOMAIN}/
  
  vscode:
    image: linuxserver/vscodium:latest
    deploy:
      replicas: 1
    networks:
      - overlaynet
    environment:
      - TZ
    volumes:
      - ${APPDATA_MNT}/vscode:/config
    labels:
      - flame.type=app
      - flame.name=VSCode
      - flame.icon=microsoft-visual-studio
      - flame.url=https://code.${DOMAIN}/

  vaultwarden:
    image: vaultwarden/server:latest
    deploy:
      replicas: 1
    networks:
      - overlaynet
    environment:
      - TZ
      - DOMAIN=https://vault.${DOMAIN}/
      - SENDS_ALLOWED='true'
      - EMERGENCY_ACCESS_ALLOWED='true'
      - WEB_VAULT_ENABLED='true'
      - SIGNUPS_ALLOWED='false'
      - SIGNUPS_VERIFY='false'
      - SIGNUPS_DOMAINS_WHITELIST=${DOMAIN}
      - YUBICO_CLIENT_ID=92307
      - YUBICO_SECRET_KEY=72o9iOvaz1yUO+6MomnE7EkPNgw=
    volumes:
      - ${APPDATA_MNT}/vaultwarden:/data
    labels:
      - flame.type=app
      - flame.name=Microbin
      - flame.icon=lock
      - flame.url=https://vault.${DOMAIN}/

  gitea:
    image: gitea/gitea:latest
    deploy:
      replicas: 1
    networks:
      - overlaynet
    environment:
      - TZ
      - PROTOCOL
      - DOMAIN
      - HTTP_PORT
      - APP_NAME
      - SHOW_USER_EMAIL
      - REVERSE_PROXY_TRUSTED_PROXIES
      - EMAIL_DOMAIN_ALLOWLIST
    volumes:
      - ${APPDATA_MNT}/gitea/config:/etc/gitea
      - ${APPDATA_MNT}/gitea/data:/var/lib/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    lables:
      - flame.type=app
      - flame.name=Microbin
      - flame.icon=git
      - flame.url=https://git.${DOMAIN}/

networks:
  overlaynet:
    external: true