---
version: "3.8"

services:

  traefik:
    image: traefik:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "80:80"
      - "8080:8080"
      - "65080:65080"
      - "443:443"
    networks:
      - overlaynet
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --serversTransport.insecureSkipVerify=true
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.swarmMode=true
      - --providers.docker.network=overlaynet
      - --providers.docker.exposedByDefault=false
      # - --providers.docker.defaultRule=Host(`{{ normalize .Name }}.cafio.co`)
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.internal.address=:65080
      - --certificatesresolvers.cf.acme.email=cfios@mf.me
      - --certificatesresolvers.cf.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.cf.acme.dnschallenge=true
      - --certificatesresolvers.cf.acme.dnschallenge.provider=cloudflare
    environment:
      TZ: ${TZ}
      CF_API_EMAIL: cfios@outlook.com
      CF_DNS_API_TOKEN: bD9fV0AK5MUEwj8nFLSnwh0zmhIODxt6-955dIRK
    volumes:
      - ${APPDATA_MNT}/traefik:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  flame:
    image: pawelmalak/flame:latest
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.routers.flame.rule: Host(`${DOMAIN}`)
        traefik.http.routers.flame.service: flame
        traefik.http.routers.flame.entrypoints: websecure
        traefik.http.services.flame.loadbalancer.server.port: 5005
        traefik.http.routers.flame.tls.certresolver: cf
    networks:
      - overlaynet
    environment:
      TZ: ${TZ}
      PASSWORD: changeme
    volumes:
      - ${APPDATA_MNT}/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

  adguard:
    image: adguard/adguardhome:latest
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.routers.adguard.rule: Host(`adguard.lan`) && ClientIP(`192.168.45.0/24`, `100.64.0.0/10`)
        traefik.http.routers.adguard.service: adguard
        traefik.http.routers.adguard.entrypoints: internal
        traefik.http.services.adguard.loadbalancer.server.port: 80
      placement:
        constraints: 
          - node.hostname == swarm0
    networks:
      - macvlan4home
    environment:
      TZ: ${TZ}
    volumes:
      - ${APPDATA_MNT}/adguard:/opt/adguardhome
    labels:
      - flame.type=app
      - flame.name=AdGuard Home
      - flame.icon=shield-check
      - flame.url=https://adguard.lan/
      - flame.visibility=hidden

networks:
  overlaynet:
    driver: overlay
    name: overlaynet
  macvlan4home:
    external: true