---
version: "3.8"

services:

  caddy:
    image: caddy:latest
    deploy:
      replicas: 1
    networks:
      - overlaynet
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    environment:
      - TZ
      - CADDYFILE
    command: sh -c 'printenv CADDYFILE > /config/Caddyfile && caddy run --config /config/Caddyfile --adapter caddyfile'
    volumes:
      - ${APPDATA_MNT}/caddy:/data
      - ${APPDATA_MNT}/caddy:/config

  flame:
    image: pawelmalak/flame:latest
    deploy:
      replicas: 1
    networks:
      - overlaynet
    environment:
      - TZ
      PASSWORD: changeme
    volumes:
      - ${APPDATA_MNT}/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

  adguard:
    image: adguard/adguardhome:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == swarm0]
    networks:
      - macvlan4home
    environment:
      - TZ
    volumes:
      - ${APPDATA_MNT}/adguard:/opt/adguardhome
    labels:
      - flame.type=app
      - flame.name=AdGuard Home
      - flame.icon=shield-check
      - flame.url=https://adguard.lan/
      - flame.visibility=hidden

  minio:
    image: minio/minio:latest
    deploy:
      mode: global
    networks:
      - overlaynet
    environment:
      - TZ
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    command: 'server /data'
    volumes:
      - ${APPDATA_MNT}/minio:/data
  
  minio-client:
    image: minio/mc
    deploy:
      replicas: 1
    networks:
      - overlaynet
    depends_on:
      - minio
    entrypoint: sh -c "mc alias set minio http://minio:9000 minioadmin minioadmin && mc mb minio/{radarr,sonarr,sabnzbd,caddy,flame,plex,gitea,vaultwarden,vscode}"

networks:
  overlaynet:
    driver: overlay
  macvlan4home:
    external: true