---
version: "3.8"

services:

  caddy:
    image: caddy:latest
    deploy:
      replicas: 1
    networks:
      - ${OVERLAY_NETWORK}
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    environment:
      CADDYFILE: |
        # Main site
        ${DOMAIN} {
          reverse_proxy flame:5005
        }

        # DoH
        agh.${DOMAIN} {
          handle /super_secret_password {
            rewrite /super_secret_password /dns-query
            reverse_proxy https://192.168.45.254:53 {
              transport http {
                tls
                tls_insecure_skip_verify
              }
            }
          }
        }

        # PairDrop reverse proxy
        drop.${DOMAIN} {
          reverse_proxy pairdrop:3000
        }

        # Nextcloud reverse proxy
        cloud.${DOMAIN} {
          reverse_proxy nextcloud:80
        }

        # OnlyOffice reverse proxy
        office.${DOMAIN} {
          reverse_proxy onlyoffice:80
        }

        # MicroBin reverse proxy
        bin.${DOMAIN} {
          reverse_proxy microbin:80
        }
       
        # VSCode reverse proxy
        code.${DOMAIN} {
          reverse_proxy vscode:3000
          basicauth {
           admin $$2a$$14$$59fq3dJu7BMgI4os7Z11sOqPUjAsZIg9QFytUDIfVR64v8NlA56Ge
          }
        }
  
        # Vaultwarden reverse proxy
        vault.${DOMAIN} {
          reverse_proxy vaultwarden:80   
        }
  
        # Gitea reverse proxy
        git.${DOMAIN} {
          reverse_proxy gitea:3000   
        }
  
        # Plex reverse proxy
        watch.${DOMAIN} {
          reverse_proxy https://plex:32400 {
            transport http {
              tls
              tls_insecure_skip_verify
            }
          }
  
          reverse_proxy /sabnzbd* sabnzbd:8080
          basicauth /sabnzbd/* {
            admin $$2a$$14$$59fq3dJu7BMgI4os7Z11sOqPUjAsZIg9QFytUDIfVR64v8NlA56Ge
          }
  
          reverse_proxy /radarr* radarr:7878
          basicauth /radarr/* {
            admin $$2a$$14$$59fq3dJu7BMgI4os7Z11sOqPUjAsZIg9QFytUDIfVR64v8NlA56Ge
          }
  
          reverse_proxy /sonarr* sonarr:8989
          basicauth /sonarr/* {
            admin $$2a$$14$$59fq3dJu7BMgI4os7Z11sOqPUjAsZIg9QFytUDIfVR64v8NlA56Ge
          }
        }
    command: sh -c 'printenv CADDYFILE > /config/Caddyfile && caddy run --config /config/Caddyfile --adapter caddyfile'
    volumes:
      - ${APP_MNT}/caddy:/data
      - ${APP_MNT}/caddy:/config
  
  flame:
    image: pawelmalak/flame:latest
    deploy:
      replicas: 1
    networks:
      - ${OVERLAY_NETWORK}
    environment:
      PASSWORD: changeme
    volumes:
      - ${APP_MNT}/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
  
networks:
  ${OVERLAY_NETWORK}:
    driver: overlay
