---
version: "3.8"

services:

  traefik:
    image: traefik:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "80:80"
      - "443:443"
    networks:
      - overlaynet
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --serversTransport.insecureSkipVerify=true
      - --api.debug=true
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.swarmMode=true
      - --providers.docker.network=overlaynet
      - --providers.docker.exposedByDefault=false
      # - --providers.docker.defaultRule=Host(`{{ normalize .Name }}.cafio.co`)
      - --entrypoints.web.address=:80
      - --entrypoints.websecured.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.cf.acme.dnschallenge=true
      - --certificatesresolvers.cf.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cf.acme.email=cfios@mailfence.com
      - --certificatesresolvers.cf.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.cf.acme.httpChallenge.entryPoint=web
    environment:
      - CF_DNS_API_TOKEN=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APPDATA_MNT}/traefik:/letsencrypt

  flame:
    image: pawelmalak/flame:latest
    deploy:
      replicas: 1
      labels:
        traefik.enable: true
        traefik.http.routers.flame.rule: Host(`${DOMAIN}`)
        traefik.http.routers.flame.entrypoints: websecure
        traefik.http.routers.flame.service: flame
        traefik.http.services.flame.loadbalancer.server.port: 5005
        traefik.http.routers.flame.tls.certresolver: cf
    networks:
      - overlaynet
    environment:
      - TZ
      PASSWORD: changeme
    volumes:
      - ${APPDATA_MNT}/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

  adguard:
    image: adguard/adguardhome:latest
    deploy:
      replicas: 1
      labels:
        traefik.enable: true
        traefik.http.routers.flame.rule: Host(`${DOMAIN}`)
        traefik.http.routers.flame.entrypoints: websecure
        traefik.http.routers.flame.service: flame
        traefik.http.services.flame.loadbalancer.server.port: 5005
        traefik.http.routers.flame.tls.certresolver: cf
      placement:
        constraints: 
          - node.hostname == swarm0
    networks:
      - macvlan4home
    environment:
      - TZ
    volumes:
      - ${APPDATA_MNT}/adguard:/opt/adguardhome
    labels:
      - flame.type=app
      - flame.name=AdGuard Home
      - flame.icon=shield-check
      - flame.url=https://adguard.lan/
      - flame.visibility=hidden

  minio:
    image: minio/minio:latest
    deploy:
      mode: global
    networks:
      - overlaynet
    environment:
      - TZ
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    command: 'server /data'
    volumes:
      - ${APPDATA_MNT}/minio:/data
  
  minio-client:
    image: minio/mc
    deploy:
      replicas: 1
    networks:
      - overlaynet
    depends_on:
      - minio
    entrypoint: sh -c "mc alias set minio http://minio:9000 minioadmin minioadmin && mc mb minio/{radarr,sonarr,sabnzbd,caddy,flame,plex,gitea,vaultwarden,vscode}"

networks:
  overlaynet:
    driver: overlay
  macvlan4home:
    external: true