---
version: "3.8"

services:

  traefik:
    image: traefik:latest
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == manager
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 8080
        published: 8080
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 65080
        published: 65080
        mode: host
    networks:
      - overlaynet
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --serversTransport.insecureSkipVerify=true
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.swarmMode=true
      - --providers.docker.network=overlaynet
      - --providers.docker.exposedByDefault=false
      # - --providers.docker.defaultRule=Host(`{{ normalize .Name }}.cafio.co`)
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.internal.address=:65080
      - --certificatesresolvers.cf.acme.email=cfios@mf.me
      - --certificatesresolvers.cf.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.cf.acme.dnschallenge=true
      - --certificatesresolvers.cf.acme.dnschallenge.provider=cloudflare
    environment:
      TZ: ${TZ}
      CF_API_EMAIL: cfios@outlook.com
      CF_DNS_API_TOKEN: bD9fV0AK5MUEwj8nFLSnwh0zmhIODxt6-955dIRK
    volumes:
      - ${APPDATA_MNT}/traefik:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  flame:
    image: pawelmalak/flame:latest
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.routers.flame.rule: Host(`${DOMAIN}`)
        traefik.http.routers.flame.service: flame
        traefik.http.routers.flame.entrypoints: websecure
        traefik.http.services.flame.loadbalancer.server.port: 5005
        traefik.http.routers.flame.tls.certresolver: cf
    networks:
      - overlaynet
    environment:
      TZ: ${TZ}
      PASSWORD: changeme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APPDATA_MNT}/flame:/app/data

  pihole:
    image: cbcrowe/pihole-unbound:latest
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.routers.pihole.rule: Host(`pi.hole`) && ClientIP(`192.168.45.0/24`, `100.64.0.0/10`)
        traefik.http.routers.pihole.service: pihole
        traefik.http.routers.pihole.entrypoints: internal
        traefik.http.services.pihole.loadbalancer.server.port: 80
      placement:
        constraints: 
          - node.labels.macvlan4home == true # Force managers because they will only have the macvlan setup
    networks:
      - macvlan4home
    cap_add: # needed if using as DHCP server
      - NET_ADMIN
    environment:
      TZ: ${TZ}
      DHCP_ACTIVE: "true"
      DHCP_START: ${NETWORK}.100
      DHCP_END: ${NETWORK}.150
      DHCP_ROUTER: ${GATEWAY}
      FTLCONF_LOCAL_IPV4: ${DNS}
      PIHOLE_DOMAIN: lan
      PIHOLE_DNS_: 127.0.0.1#5335
      WEBPASSWORD: changeme
      WEBTHEME: default-dark 
      DNSSEC: "true"
      DNSMASQ_LISTENING: local
    volumes:
      - ${APPDATA_MNT}/pihole:/etc/pihole:rw
      - ${APPDATA_MNT}/pihole/unbound:/etc/dnsmasq.d:rw
    labels:
      - flame.type=app
      - flame.name=PiHole
      - flame.icon=pi-hole
      - flame.url=http://pi.hole/
      - flame.visibility=hidden

networks:
  overlaynet:
    driver: overlay
    name: overlaynet
  macvlan4home:
    external: true