---
version: "3.8"

services:

  plex:
    image: plexinc/pms-docker:latest
    deploy:
      replicas: 1
    networks:
      - overlaynet
    environment:
      - TZ
      - PLEX_CLAIM
      - ADVERTISE_IP
      - ALLOWED_NETWORKS
    volumes:
      - plex:/config
      - ${MEDIA_MNT}:/media:ro
    tmpfs:
      - /transcode
    labels:
      - flame.type=app
      - flame.name=Plex
      - flame.icon=plex
      - flame.url=https://watch.${DOMAIN}/

  radarr:
    image: hotio/radarr:latest
    deploy:
      replicas: 1
    networks:
      - overlaynet
    environment:
      - TZ
    depends_on:
      - sabnzbd
    volumes:
      - radarr:/config
      - ${MEDIA_MNT}:/data
    labels:
      - flame.type=app
      - flame.name=Radarr
      - flame.icon=movie-open
      - flame.url=https://watch.${DOMAIN}/radarr/
      - flame.visibility=hidden

  sonarr:
    image: hotio/sonarr:latest
    deploy:
      replicas: 1
    networks:
      - overlaynet
    environment:
      - TZ
    depends_on:
      - sabnzbd
    volumes:
      - sonarr:/config
      - ${MEDIA_MNT}:/data
    labels:
      - flame.type=app
      - flame.name=Sonarr
      - flame.icon=youtube-tv
      - flame.url=https://watch.${DOMAIN}/sonarr/
      - flame.visibility=hidden

  sabnzbd:
    image: hotio/sabnzbd:latest
    deploy:
      replicas: 1
    networks:
      - overlaynet
    environment:
      - TZ
    volumes:
      - sabnzbd:/config
      - ${MEDIA_MNT}:/data
    labels:
      - flame.type=app
      - flame.name=Sabnzbd
      - flame.icon=cloud-download
      - flame.url=https://watch.${DOMAIN}/sabnzbd/
      - flame.visibility=hidden

volumes:
  plex:
    driver: rclone
    driver_opts:
      config: ./rclone.conf
      remote: minio:appdata/plex
  radarr:
    driver: rclone
    driver_opts:
      config: ./rclone.conf
      remote: minio:appdata/radarr
  sonarr:
    driver: rclone
    driver_opts:
      config: ./rclone.conf
      remote: minio:appdata/sonarr
  sabnzbd:
    driver: rclone
    driver_opts:
      config: ./rclone.conf
      remote: minio:appdata/sabnzbd

networks:
  overlaynet:
    external: true