---
version: "3.8"

services:

  plex:
    image: plexinc/pms-docker:latest
    deploy:
      replicas: 1
    networks:
      - overlaynet
    environment:
      - TZ
      - PLEX_CLAIM
      - ADVERTISE_IP
      - ALLOWED_NETWORKS
    volumes:
      - ${APPDATA_MNT}/gitea/plex:/config
      - ${MEDIA_MNT}:/media:ro
    tmpfs:
      - /transcode
    labels:
      - flame.type=app
      - flame.name=Plex
      - flame.icon=plex
      - flame.url=https://watch.${DOMAIN}/

  radarr:
    image: hotio/radarr:latest
    deploy:
      replicas: 1
      labels:
        traefik.enable: true
        traefik.http.routers.radarr.rule: Host(`watch.${DOMAIN}`) && PathPrefix ('/radarr')
        traefik.http.routers.radarr.service: radarr
        traefik.http.routers.radarr.entrypoints: websecure
        traefik.http.services.radarr.loadbalancer.server.port: 7878
        traefik.http.routers.radarr.tls.certresolver: cf
    networks:
      - overlaynet
    environment:
      - TZ
    depends_on:
      - sabnzbd
    volumes:
      - ${APPDATA_MNT}/gitea/radarr:/config
      - ${MEDIA_MNT}:/data
    labels:
      - flame.type=app
      - flame.name=Radarr
      - flame.icon=movie-open
      - flame.url=https://watch.${DOMAIN}/radarr/
      - flame.visibility=hidden

  sonarr:
    image: hotio/sonarr:latest
    deploy:
      replicas: 1
      labels:
        traefik.enable: true
        traefik.http.routers.sonarr.rule: Host(`watch.${DOMAIN}`) && PathPrefix ('/sonarr')
        traefik.http.routers.sonarr.service: sonarr
        traefik.http.routers.sonarr.entrypoints: websecure
        traefik.http.services.sonarr.loadbalancer.server.port: 8989
        traefik.http.routers.sonarr.tls.certresolver: cf
    networks:
      - overlaynet
    environment:
      - TZ
    depends_on:
      - sabnzbd
    volumes:
      - ${APPDATA_MNT}/gitea/sonarr:/config
      - ${MEDIA_MNT}:/data
    labels:
      - flame.type=app
      - flame.name=Sonarr
      - flame.icon=youtube-tv
      - flame.url=https://watch.${DOMAIN}/sonarr/
      - flame.visibility=hidden

  sabnzbd:
    image: hotio/sabnzbd:latest
    deploy:
      replicas: 1
      labels:
        traefik.enable: true
        traefik.http.routers.sabnzbd.rule: Host(`watch.${DOMAIN}`) && PathPrefix ('/sabnzbd')
        traefik.http.routers.sabnzbd.service: sabnzbd
        traefik.http.routers.sabnzbd.entrypoints: websecure
        traefik.http.services.sabnzbd.loadbalancer.server.port: 8080
        traefik.http.routers.sabnzbd.tls.certresolver: cf
    networks:
      - overlaynet
    environment:
      - TZ
    volumes:
      - ${APPDATA_MNT}/gitea/sabnzbd:/config
      - ${MEDIA_MNT}:/data
    labels:
      - flame.type=app
      - flame.name=Sabnzbd
      - flame.icon=cloud-download
      - flame.url=https://watch.${DOMAIN}/sabnzbd/
      - flame.visibility=hidden

networks:
  overlaynet:
    external: true