---
version: "3.8"

services:

  plex:
    image: linuxserver/plex:latest
    deploy:
      replicas: 1
      labels:
        caddy: watch.cafio.co
        caddy.reverse_proxy: "{{upstreams https 32400}}"
        caddy.reverse_proxy.transport: http
        caddy.reverse_proxy.transport.tls:
        caddy.reverse_proxy.transport.tls_insecure_skip_verify:
        homepage.group: Media
        homepage.name: Plex
        homepage.icon: plex
        homepage.href: https://watch.cafio.co/
        homepage.description: Media Server
    networks:
      - overlaynet
    environment:
      TZ: $TZ
      PLEX_CLAIM: $PLEX_CLAIM #https://plex.tv/claim
      ADVERTISE_IP: https://swarm.lan:32400,https://$NETBIRDIP:32400,https://watch.$DOMAIN:443
      ALLOWED_NETWORKS: 192.168.45.0/24,100.64.0.0/10,10.0.0.0/8
    volumes:
      - $APPDATA_MNT/plex:/config
      - $MEDIA_MNT:/data/media:ro
    tmpfs:
      - /transcode
    labels:
      - flame.type=app
      - flame.name=Plex
      - flame.icon=plex
      - flame.url=https://watch.$DOMAIN/

  radarr:
    image: hotio/radarr:latest
    deploy:
      replicas: 1
      labels:
        caddy: cafio.co
        caddy.reverse_proxy: /radarr* "{{upstreams 7878}}"
        homepage.group: Media
        homepage.name: Radarr
        homepage.icon: radarr
        homepage.href: https://cafio.co/radarr/
        homepage.description: Movie manager
    networks:
      - overlaynet
    environment:
      TZ: $TZ
      PUID: 1001
      PGID: 1002
      UMASK: 002
    depends_on:
      - sabnzbd
    volumes:
      - $APPDATA_MNT/radarr:/config
      - $MEDIA_MNT:/data

  sonarr:
    image: hotio/sonarr:latest
    deploy:
      replicas: 1
      labels:
        caddy: cafio.co
        caddy.reverse_proxy: /sonarr* "{{upstreams 8989}}"
        homepage.group: Media
        homepage.name: Sonarr
        homepage.icon: sonarr
        homepage.href: https://cafio.co/sonarr/
        homepage.description: TV Show manager
    networks:
      - overlaynet
    environment:
      TZ: $TZ
      PUID: 1001
      PGID: 1002
      UMASK: 002
    depends_on:
      - sabnzbd
    volumes:
      - $APPDATA_MNT/sonarr:/config
      - $MEDIA_MNT:/data

  sabnzbd:
    image: hotio/sabnzbd:latest
    deploy:
      replicas: 1
      labels:
        caddy: cafio.co
        caddy.reverse_proxy: /sabnzbd* "{{upstreams 8080}}"
        caddy.basicauth: /sabnzbd*
        caddy.basicauth.swarm: $$2a$$12$$8V1u/O/1LuzQDcV56hxX0ekowne/RKeBi6jlT1vLNo0DkdQbFrnKm
        homepage.group: Media
        homepage.name: Sabnzbd
        homepage.icon: sabnzbd
        homepage.href: https://cafio.co/sabnzbd/
        homepage.description: 🏴‍☠️
    networks:
      - overlaynet
    environment:
      TZ: $TZ
      PUID: 1001
      PGID: 1002
      UMASK: 002
    volumes:
      - $APPDATA_MNT/sabnzbd:/config
      - $MEDIA_MNT/usenet:/data/usenet

networks:
  overlaynet:
    external: true
