---
version: "3.8"

services:

  plex:
    image: plexinc/pms-docker:latest
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.routers.plex.rule: Host(`watch.${DOMAIN}`)
        traefik.http.routers.plex.service: plex
        traefik.http.routers.plex.entrypoints: websecure
        traefik.http.services.plex.loadbalancer.server.port: 32400
        traefik.http.routers.plex.tls.certresolver: cf
    networks:
      - overlaynet
    environment:
      TZ: ${TZ}
      PLEX_CLAIM:  #https://plex.tv/claim
      ADVERTISE_IP: https://${HOSTNAME}.lan:32400,https://${TAILSCALEIP}:32400,https://watch.${DOMAIN}:443
      ALLOWED_NETWORKS: ${SUBNET},100.64.0.0/255.192.0.0,10.0.0.0/255.0.0.0
    volumes:
      - ${APPDATA_MNT}/plex:/config
      - ${MEDIA_MNT}:/data:ro
    tmpfs:
      - /transcode
    labels:
      - flame.type=app
      - flame.name=Plex
      - flame.icon=plex
      - flame.url=https://watch.${DOMAIN}/

  radarr:
    image: hotio/radarr:latest
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.routers.radarr.rule: Host(`radarr.${DOMAIN}`) && ClientIP(`192.168.45.0/24,100.64.0.0/10`)
        traefik.http.routers.radarr.service: radarr
        traefik.http.routers.radarr.entrypoints: websecure
        traefik.http.services.radarr.loadbalancer.server.port: 7878
        traefik.http.routers.plex.tls.certresolver: cf
    networks:
      - overlaynet
    environment:
      TZ: ${TZ}
    depends_on:
      - sabnzbd
    volumes:
      - /mnt/cluster/appdata/radarr:/config
      - ${MEDIA_MNT}:/data
    labels:
      - flame.type=app
      - flame.name=Radarr
      - flame.icon=movie-open
      - flame.url=https://watch.${DOMAIN}/radarr/
      - flame.visibility=hidden

  sonarr:
    image: hotio/sonarr:latest
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.routers.sonarr.rule: Host(`sonarr.${DOMAIN}`) && ClientIP(`192.168.45.0/24,100.64.0.0/10`)
        traefik.http.routers.sonarr.service: sonarr
        traefik.http.routers.sonarr.entrypoints: websecure
        traefik.http.services.sonarr.loadbalancer.server.port: 8989
        traefik.http.routers.plex.tls.certresolver: cf
    networks:
      - overlaynet
    environment:
      TZ: ${TZ}
    depends_on:
      - sabnzbd
    volumes:
      - /mnt/cluster/appdata/sonarr:/config
      - ${MEDIA_MNT}:/data
    labels:
      - flame.type=app
      - flame.name=Sonarr
      - flame.icon=youtube-tv
      - flame.url=https://watch.${DOMAIN}/sonarr/
      - flame.visibility=hidden

  sabnzbd:
    image: hotio/sabnzbd:latest
    deploy:
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.routers.sabnzbd.rule: Host(`sabnzbd.${DOMAIN}`) && ClientIP(`192.168.45.0/24,100.64.0.0/10`)
        traefik.http.routers.sabnzbd.service: sabnzbd
        traefik.http.routers.sabnzbd.entrypoints: websecure
        traefik.http.services.sabnzbd.loadbalancer.server.port: 8080
        traefik.http.routers.plex.tls.certresolver: cf
    networks:
      - overlaynet
    environment:
      TZ: ${TZ}
    volumes:
      - /mnt/cluster/appdata/sabnzbd:/config
      - ${MEDIA_MNT}:/data
    labels:
      - flame.type=app
      - flame.name=Sabnzbd
      - flame.icon=cloud-download
      - flame.url=https://watch.${DOMAIN}/sabnzbd/
      - flame.visibility=hidden

networks:
  overlaynet:
    external: true